# Generated by Django 4.2.6 on 2023-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plates", models.IntegerField()),
                ("pipes", models.IntegerField()),
                ("rod", models.IntegerField()),
            ],
        ),
    ]
